clusters:
  - vpc: vpc-central
    worker_count: 3 
    machine_type: n1-standard-4
    zones: 
    - us-central1-a
    - us-central1-b
    - us-central1-c
    expose_ui: True
  - vpc: vpc-east
    worker_count: 3 
    machine_type: t2.xlarge 
    zones: 
    - us-east-1c
    - us-east-1c
    - us-east-1c
    expose_ui: False
networks:
  - name: vpc-central
    public_cidr: 10.1.0.0/24
    private_cidr: 10.2.0.0/16 
    region: us-central1
    bastion_zone: us-central1-f
    rack_aware: True
    provider: gcp
  - name: vpc-east
    vpc_cidr: 10.0.0.0/16
    public_cidr: 10.0.1.0/24
    private_cidr: 10.0.2.0/24
    region: us-east-1 
    bastion_zone: us-east-1c
    provider: aws
    zone: us-east-1c
