clusters:
  - vpc: vpc-central
    worker_count: 3 
    machine_type: n1-standard-4
    zones: 
    - us-central1-a
    - us-central1-b
    - us-central1-c
    expose_ui: True
  - vpc: vpc-east
    worker_count: 3 
    machine_type: n1-standard-4
    zones: 
    - us-east1-d
    - us-east1-b
    - us-east1-c
    expose_ui: True
networks:
  - name: vpc-central
    public_cidr: 10.1.0.0/24
    private_cidr: 10.2.0.0/16 
    region: us-central1
    bastion_zone: us-central1-f
    rack_aware: True
  - name: vpc-east
    public_cidr: 10.1.0.0/24
    private_cidr: 10.2.0.0/16
    region: us-east1 
    bastion_zone: us-east1-c
