---
clusters:
  - vpc: vpc-aws-us
    worker_count: 3 
    machine_type: t2.xlarge
    machine_image: ami-05f238ddab9a512be
    zones: 
    - us-east-1a
    - us-east-1b
    - us-east-1c
    expose_ui: True
  - vpc: vpc-gcp
    worker_count: 3 
    machine_type: n1-standard-4
    machine_image: rhel-8-v20210721
    zones: 
    - europe-west3-a
    - europe-west3-b
    - europe-west3-c
    expose_ui: True
networks:
  - name: vpc-aws-us
    vpc_cidr: 10.1.0.0/16
    public_cidr: 10.1.1.0/24
    private_cidr: 
      us-east-1a: 10.1.3.0/24
      us-east-1b: 10.1.2.0/24
      us-east-1c: 10.1.4.0/24
    region: us-east-1
    rack_aware: False
    bastion_zone: us-east-1c
    bastion_machine_image: ami-0b1db37f0fa006678
    bastion_machine_type: t2.micro
    provider: aws
    redis_distro: https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.6/redislabs-6.2.6-7-rhel8-x86_64.tar
  - name: vpc-gcp
    public_cidr: 10.1.0.0/24
    private_cidr: 10.2.0.0/16 
    region: europe-west3
    bastion_zone: europe-west3-b
    bastion_machine_image: rhel-7-v20210721
    bastion_machine_type: n1-standard-1
    rack_aware: True
    provider: gcp
    redis_distro: https://s3.amazonaws.com/redis-enterprise-software-downloads/6.2.6/redislabs-6.2.6-7-rhel8-x86_64.tar
nameservers:
  - vpc: vpc-aws-us
    parent_zone: aws.ps-redislabs.com
    domain: aws.ps-redislabs.com
    provider: aws
  - vpc: vpc-gcp
    parent_zone: ps-redislabs
    domain: ps-redislabs.com
    provider: gcp
